### ISSUE TITLE
rsocket-rpc-protobuf binaries not getting published for MacOS

### ISSUE THREAD

**Issue by jareddellitt** [rsocket/rsocket-rpc-java#36]
I've been trying to get the latest version working on MacOS, but It looks like the last version of `rsocket-rpc-protobuf` published with osx binaries was 0.2.10:

`rsocket-rpc-protobuf-0.2.10-osx-x86_64.exe`

Just curious if this was intentional or maybe an oversight.

**Comment by robertroeser** [comment]
Hi @jareddellitt ,

I checked and the 0.2.10 binaries are on Maven Central:
https://repo1.maven.org/maven2/io/rsocket/rpc/rsocket-rpc-protobuf/0.2.10/
https://repo1.maven.org/maven2/io/rsocket/rpc/rsocket-rpc-protobuf/0.2.10/rsocket-rpc-protobuf-0.2.10-osx-x86_64.exe

Out of curiosity where are you pulling the binaries from?

Thanks,
Robert

**Comment by robertroeser** [comment]
Hi @jareddellitt,

It does appear that the binaries didn't get synced correctly. Will look into this.

Thanks,
Robert

**Comment by robertroeser** [comment]
Quick update - I opened a support ticket with bintray - hopefully they can get this fixed soon. A work around in the mean time is to use jcenter.

Thanks,
Robert

**Comment by mostroverkhov** [comment]
rsocket rpc compiler 0.2.18 is published on `jcenter` for linux, osx and windows platforms http://jcenter.bintray.com/io/rsocket/rpc/rsocket-rpc-protobuf/0.2.18/
