### ISSUE TITLE
Compile with JetBrains / gradle-intellij-plugin fails

### ISSUE THREAD

**Issue by d-wojciechowski** [rsocket/rsocket-rpc-java#57]
## Expected Behavior
A project with both gradle-intellij-plugin and rsocket-rpc compile successfully. 
## Current Behavior

When both gradle-intellij-plugin and rsocket-rpc are configured in Gradle build file, build process fails on compileJava with the following message (for readability on Pastebin, and attached below) 
[out-error.log](https://github.com/rsocket/rsocket-rpc-java/files/4090897/out-error.log)
[out.log](https://github.com/rsocket/rsocket-rpc-java/files/4090898/out.log)
[Pastebin](https://pastebin.com/DY4NWWLg)

## Steps to Reproduce
1. Pull example repository [github](https://github.com/DominikWojciechowski/exampleProjectForIssue)
2. install protoc on your machine (please follow this link [protobuf](https://github.com/protocolbuffers/protobuf) or use a handy tool like [chocolatey](https://chocolatey.org/)
3. Import project to IntelliJ IDEA 
4. Execute Gradle tasks "clean" and "build"
5. Observe error message on the console 😉 
6. Copy contents from "buildWithoutIntellijPlugin.gradle.kts" to "build.gradle.kts"
7. Execute Gradle tasks "clean" and "build"
8. Build should pass this time.

## Context (Environment)

I am implementing [opensource plugin](https://gitlab.com/wojciechowskid/wncplugin) to IntelliJ idea which will connect to another program on another machine via rsocket-rpc. I need to have generated and compiled java files o be able to use RPC goodness. 

## Detailed Description

I have no experience in Gradle plugin development and I am not able to find out where exactly the problem is. Maybe in the debug session, there would be a possibility to find an exact solution

**Comment by gregwhitaker** [comment]
This looks like it may be an issue with the version of protoc. I'll take a look at it and see what I can find.

**Comment by d-wojciechowski** [comment]
Hey, It seems that it may not be related to rsocket-rpc-java. [issue on gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin/issues/456)

I am not sure what may be the followup of this ticket. Should I close it?
