### ISSUE TITLE
Cannot build the master in MAC

### ISSUE THREAD

**Issue by ilterpehlivan** [rsocket/rsocket-rpc-java#61]
Hi,

I am trying to build the codes but C++ compilation part is giving some errors

Here is the errors:

> Task :rsocket-rpc-protobuf:compileJava_pluginExecutableJava_pluginCpp FAILED
In file included from /Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.cc:4:
/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.h:118:56: error: only virtual member functions can be marked 'final'
      ::google::protobuf::io::CodedInputStream* input) final;
                                                       ^~~~~
/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.h:120:64: error: only virtual member functions can be marked 'final'
      ::google::protobuf::io::CodedOutputStream* output) const final;
                                                               ^~~~~
/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.h:122:68: error: only virtual member functions can be marked 'final'
      bool deterministic, ::google::protobuf::uint8* target) const final;
                                                                   ^~~~~
/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.cc:11:10: fatal error: 'google/protobuf/wire_format_lite_inl.h' file not found
#include <google/protobuf/wire_format_lite_inl.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.

/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.h:118:56: error: only virtual member functions can be marked 'final'
      ::google::protobuf::io::CodedInputStream* input) final;
                                                       ^~~~~
/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.h:120:64: error: only virtual member functions can be marked 'final'
      ::google::protobuf::io::CodedOutputStream* output) const final;
                                                               ^~~~~
/Users/user/Development/test-area/rsocket-rpc-java/rsocket-rpc-protobuf/src/java_plugin/cpp/rsocket/options.pb.h:122:68: error: only virtual member functions can be marked 'final'
      bool deterministic, ::google::protobuf::uint8* target) const final;

*******************
Not sure it is related to my environment 

OSX
C++ - 11

Thanks

**Comment by ilterpehlivan** [comment]
Seems first need to build "rsocket-rpc-protobuf-idl" and copy the generated 2 options..h/cpp files into "rsocket-rpc-protobuf" then it works

**Comment by OlegDokuka** [comment]
Hi @ilterpehlivan. In order to compile rsocket-rpc you have to have installed protobuf 3.6.x. It does not compile with the higher versions of the framework

**Comment by ilterpehlivan** [comment]
Thanks for the clarification and prompt answer @OlegDokuka 
In the Readme, it says "RSocket RPC requires Protobuf 3.6.x or higher." which is misleading
Also maybe it is possible to generate those options cpp files and use it during the build, then it will arise the 3.6 version dependency!
Good to have feature.. anyway closing this one
