### ISSUE TITLE
Improved metadata handling

### ISSUE THREAD

**Issue by regbo** [rsocket/rsocket-rpc-java#62]
I created a library that allows for compositemetadata to be used:
https://github.com/regbo/lfp-rsocket-ipc-metadata

It comes with a few other features, but I think the method used could be used here to improve current support. Have a look and LMK if you ave any questions.

**Comment by OlegDokuka** [comment]
Hey @regbo. 

Work on CompositeMetadata support is done in #44 PR. 
As of now, I don't have enough time to finalize it but in general, it is ready to be used.

Feel free to check out and test is locally

**Comment by regbo** [comment]
Awesome thanks!

**Comment by OlegDokuka** [comment]
If you see how to improve the existing project, feel free to contribute.

PRs are welcome

**Comment by regbo** [comment]
Hi @OlegDokuka I created a PR (#63)
