### ISSUE TITLE
RSocket RPC 0.3.0 version is not available on maven central

### ISSUE THREAD

**Issue by mavocitrix** [rsocket/rsocket-rpc-java#73]
There was a new release marked 0.3.0 https://github.com/rsocket/rsocket-rpc-java/releases/tag/0.3.0 and I wanted to give it a try, but it seems that it was not uploaded to mavencentral. Last version in https://mvnrepository.com/artifact/io.rsocket.rpc/rsocket-rpc-core is 0.2.19.

Are there any plans to upload it? 
Thanks
Matous

**Comment by OlegDokuka** [comment]
should be available now. thank you for reporting that

**Comment by mavocitrix** [comment]
Thanks for quick fix!

**Comment by mavocitrix** [comment]
I have a followup question regarding the upgrade: https://stackoverflow.com/questions/66119704/what-happened-to-fragmentationduplexconnection
